name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Analysing the code with pylint
      uses: kgpl/gh-pylint@v1
      with:
        package-path: .
        python-version: '3.11'

