name: Pylint

on: [push]

env:
  python-version: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      uses: kgpl/gh-pylint@v1
      with:
        package-path: .
        python-version: ${{ matrix.python-version }}

