name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Analysing the code with pylint
      uses: Silleellie/pylint-github-action@v3
      with:
        lint-path: .
        python-version: 3.11

